### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by planemad** [maxlath/wikidata-cli#34]
Getting this error when I try to run any command on wikidata-cli. For background, I just installed the module and using node v8.

Does not work with sudo either, what could be wrong?

```
planemad:dashboards arun$ wd summary Q42
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:499:9)
    at Command.executeSubCommand (/usr/local/lib/node_modules/wikidata-cli/node_modules/commander/index.js:552:14)
    at Command.parse (/usr/local/lib/node_modules/wikidata-cli/node_modules/commander/index.js:477:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/wikidata-cli/bin/wd:63:2)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by maxlath** [comment]
hi!
We have seen those [in the past](https://github.com/maxlath/wikidata-cli/issues?q=is%3Aissue+EACCES+is%3Aclosed), let's see were it could come from:
* Do you have the same error when running `wd props`?
* What does `wd config path` output? Do you have write rights on this folder?
* Are all the files in the `/usr/local/lib/node_modules/wikidata-cli` marked as executables?

**Comment by planemad** [comment]
- `wd props` gives the EACCES error
- `wd config path` gives the EACCES error
- Yes except index.js . I fixed this with `chmod +x index.js`, but still get the EACCESS error <br><img width="483" alt="screen shot 2017-11-02 at 3 48 30 pm" src="https://user-images.githubusercontent.com/126868/32332402-b30ea6e0-bfe5-11e7-89c3-b9de854afea5.png">

**Comment by maxlath** [comment]
sorry, my mistake, I meant `/usr/local/lib/node_modules/wikidata-cli/bin`, but the issue with `wd props` an `wd config path` hint that there is something more fundamentally wrong with the install anyway: did you try to reinstall it? I don't see how it could end up differently, but it doesn't cost much to try

Otherwise, I generally recommend to install node with [`nvm`](https://github.com/creationix/nvm): in addition to giving greater control of the node version, it installs the global executables in a folder in your home folder (ex: `~/.nvm/versions/node/v8.2.1/bin/wd`), thus avoiding the need to use sudo and the associated `EACCESS` errors

**Comment by planemad** [comment]
@maxlath got it working with a `chmod +x bin/*`  👍 

` wd config path` gives `/usr/local/lib/node_modules/wikidata-cli/config.json`. Also my node is installed via nvm.
